# Generated by Django 4.1.3 on 2022-11-14 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votehelperapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='decision',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='voter',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
