# Generated by Django 4.1.3 on 2022-12-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votehelperapp', '0005_remove_voter_neighbourhood_delete_neighbourhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='neighbourhood',
            field=models.TextField(default='t'),
        ),
    ]
