# Generated by Django 4.1.3 on 2022-12-20 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votehelperapp', '0006_voter_neighbourhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='neighbourhood',
            field=models.TextField(blank=True, default='t'),
        ),
    ]
