# Generated by Django 4.1.3 on 2022-12-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votehelperapp', '0007_alter_voter_neighbourhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='assignedEmp',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='voter',
            name='neighbourhood',
            field=models.TextField(blank=True, default=''),
        ),
    ]
