# Generated by Django 4.1.3 on 2023-01-01 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votehelperapp', '0008_voter_assignedemp_alter_voter_neighbourhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='email',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='voter',
            name='phone',
            field=models.TextField(blank=True, default=''),
        ),
    ]
