# Generated by Django 4.1.3 on 2023-01-17 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('votehelperapp', '0009_voter_email_voter_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='voter',
            old_name='neighbourhood',
            new_name='group',
        ),
    ]
